### ISSUE TITLE
Spark 3 support?

### ISSUE THREAD

**Issue by mpfishe2** [googleapis/java-pubsublite-spark#160]
I was just wondering when this connector will work with Spark 3.x? I have some projects that have been migrated to Spark 3.x / Scala 2.12 and so I cannot leverage this connector to build Structured Streaming pipelines with Pub Sub Lite.

**Comment by mpfishe2** [comment]
Any updates on whether there will be a connector that support this for Spark 3.x+?

**Comment by jiangmichaellll** [comment]
Hi Max,

We don't have a concrete plan yet to support this for Spark 3.x+, but I have seen trending adoption into Spark 3.x so I will bring this up internally and keep you posted.

Thanks,
Michael

**Comment by davilayang** [comment]
Hey Michael, 

Curious on whether this is in progress or not? We have plan to use Dataproc with Structured Streaming and Pub/Sub Lite, but the compatibility issue seems to make that undoable. Do you know when will that happen?

Thanks

**Comment by elliot42** [comment]
+1, this make the connector unusable on any recent version of Spark, including the Dataproc 2.0 image series.  The Dataproc 1.5 series, even if you wanted to use it, is only supported through the end of this year 2022 (1.4 support just expired): 

https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions
