### ISSUE TITLE
Support multiple scala versions

### ISSUE THREAD

**Issue by hayssams** [googleapis/java-pubsublite-spark#207]
In the pom.xml file, 
the dependency to scala-java8-compat is explicitly set to scala-java8-compat_2.11 which makes this library dependent on scala 2.11 even if Spark is set as provided in that same file.

I see 3 options:
## Option 1: Do not use scala-java8-compat
What's the alternative then ?

## Option 2: set scala version in the dependency name
Replace  `<artifactId>scala-java8-compat_2.11</artifactId>` by `<artifactId>scala-java8-compat_${scala.version.short}</artifactId>` and set it as provided, requiring the user to add the dependency to the right (scala) version of scala-java8-compat     

I currently recompile your code locally with the pom.xml updated as follows:
```    
<dependency>
      <groupId>org.scala-lang.modules</groupId>
      <artifactId>scala-java8-compat_${scala.version.short}</artifactId>
      <version>1.0.0</version>
      <scope>provided</scope>
</dependency>
```

## Option 3: cross compile this library to multiple scala versions
This would require to upgrade upgrade the build section to something similar to https://davidb.github.io/scala-maven-plugin/example_java.html

My preference goes to Option 2. Let me know if you would accept such a PR.

**Comment by jiangmichaellll** [comment]
Hi Hayssam,

Thanks for bringing this up! Option 2 makes sense to me, I created https://github.com/googleapis/java-pubsublite-spark/pull/209 for this.

Thanks,
Michael

**Comment by jiangmichaellll** [comment]
https://github.com/googleapis/java-pubsublite-spark/pull/209 is checked in and will be in next release.
